name: claracore

services:
  claracore:
    build:
      context: ..
      dockerfile: docker-cuda/Dockerfile.cuda
    container_name: claracore
    image: claracore:cuda
    restart: unless-stopped
    ports:
      - "5890:5890"
    volumes:
      # Persistent volume for downloaded models
      - claracore-downloads:/app/downloads
      
      # Optional: Bind mount your own model folders
      # Uncomment and customize the paths below to use your existing models
      # - /path/to/your/models:/app/models:ro          # Read-only access
      # - /mnt/storage/llm-models:/app/external:ro     # Another folder
      # - ~/ai-models:/app/my-models:ro                # Home directory models
      
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  # Persistent storage for downloaded models only
  # This volume persists even after 'docker-compose down'
  # To delete: docker-compose down -v (WARNING: deletes all downloaded models!)
  claracore-downloads:
    name: claracore-downloads

# ============================================================
# 📁 BINDING YOUR OWN MODEL FOLDERS
# ============================================================
# To use your existing model folders, uncomment the volume binds above
# and replace the paths with your actual directories:
#
# Examples:
#   Linux:   - /mnt/data/models:/app/models:ro
#   Windows: - C:\Users\YourName\Models:/app/models:ro
#   macOS:   - /Users/yourname/ai-models:/app/models:ro
#
# Tips:
#   - Use :ro (read-only) to prevent accidental modifications
#   - You can mount multiple folders to different paths
#   - After adding folders, go to Setup and scan them
#   - Paths inside container: /app/models, /app/external, etc.
#
# ============================================================
